export const pointMissions = [
  {
    key: "hirano",
    label: "平野と写真",
    points: 20,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "平野との写真を撮る!!",
    exampleUrl: "/examples/hirano.jpg",
  },
  {
    key: "tokuriki",
    label: "徳力と写真",
    points: 30,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "徳力との写真を撮る!!",
    exampleUrl: "/examples/tokuriki.jpg",
  },
  {
    key: "matsui",
    label: "松井と写真",
    points: 10,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "松井との写真を撮る!!",
    exampleUrl: "/examples/matsui.jpg",
  },
  {
    key: "follower",
    label: "フォロワー獲得",
    points: 20,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "フォローした画面のスクショ",
    exampleUrl: "/examples/follower.jpg",
  },
  {
    key: "gomiboke",
    label: "ゴミボケ",
    points: 5,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "ゴミを使った面白い写真",
    exampleUrl: "/examples/gomiboke.jpg",
  },
  {
    key: "dance",
    label: "ばくれつダンス",
    points: 50,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "video",
    adminOnly: false,
    description: "ダンスしている動画",
    exampleUrl: "/examples/dance.mp4",
  },
  {
    key: "danceArrange",
    label: "アレンジありばくれつダンス",
    points: 70,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "video",
    adminOnly: false,
    description: "アレンジしたダンス動画",
    exampleUrl: "/examples/danceArrange.mp4",
  },
  {
    key: "pose",
    label: "ポーズ写真",
    points: 10,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "指定ポーズで撮影した写真",
    exampleUrl: "/examples/pose.jpg",
  },
  {
    key: "foreign",
    label: "外国人と掃除",
    points: 15,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "外国人と一緒に掃除している様子",
    exampleUrl: "/examples/foreign.jpg",
  },
  {
    key: "lunch",
    label: "昼ごはん投稿",
    points: 10,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "昼ごはん投稿のスクショ",
    exampleUrl: "/examples/lunch.jpg",
  },
  {
    key: "child",
    label: "子どもとゴミ拾い",
    points: 15,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: false,
    description: "子どもと一緒にゴミ拾いしている様子",
    exampleUrl: "/examples/child.jpg",
  },
  {
    key: "bags",
    label: "ゴミ袋",
    points: 10,
    requiresQuantity: true,
    requiresEvidence: false,
    evidenceType: "image",
    adminOnly: false,
    description: "集めたゴミ袋の数を入力してください",
    exampleUrl: "",
  },
  {
    key: "gomibokeSpecial",
    label: "ゴミボケ（20pt）",
    points: 20,
    requiresQuantity: false,
    requiresEvidence: true,
    evidenceType: "image",
    adminOnly: true,
    description: "特に面白いゴミボケ（管理者判断）",
    exampleUrl: "/examples/gomiboke.jpg",
  },

  {
  key: "zukan",
  label: "ゴミ図鑑投稿",
  points: 5,
  requiresQuantity: false,
  requiresEvidence: true,
  evidenceType: "image",
  adminOnly: false,
  description: "ゴミ図鑑に投稿",
  exampleUrl: "",
},

];
export function getMissionByKey(key: string) {
  return pointMissions.find((m) => m.key === key);
}


